letsdine/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

app_name = 'letsdine'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^login/$', auth_views.login, {'template_name': 'letsdine/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,{'next_page': '/'}, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^addplan/$', views.add_plan, name='add_plan'),
    url(r'^editprofile/$', views.edit_profile, name='editprofile'),
    url(r'^profile/(?P<username>\w+)/$', views.profile, name='profile'),
    url(r'^cancelplan/(?P<plan_id>[0-9]+)/$', views.cancelplan, name='cancelplan'),
    url(r'^confirmplan/(?P<plan_id>[0-9]+)/$', views.confirmplan, name='confirmplan'),
    url(r'^requestplan/(?P<plan_id>[0-9]+)/$', views.requestplan, name='requestplan'),
    url(r'^rejectplan/(?P<plan_id>[0-9]+)/$', views.rejectplan, name='rejectplan'),
    url(r'^search/$', views.search, name='search'),
]

sdshackathon/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from letsdine.views import UserAutocomplete

urlpatterns = [
    url(r'^', include('letsdine.urls')),
    url(r'^admin/', admin.site.urls),
    url(
        r'^user-autocomplete/$',
        UserAutocomplete.as_view(),
        name='user-autocomplete',
    ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

letsdine/models.py
from __future__ import unicode_literals
from django.utils import timezone
#from django.db import models
from django.contrib.auth.models import User
from django.contrib.gis.db import models

# Create your models here.

class Intrest(models.Model):
  name = models.CharField(max_length=40)
  def __str__(self):
   return self.name

class UserProfile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE) 
  display_pic = models.ImageField(default='pic_folder/user.jpg' , upload_to = 'pic_folder/',null=True, blank=True,)
  contact_no = models.BigIntegerField(default=000000000,blank=True )
  city_name = models.CharField(max_length=40, blank=True)
  Gender_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other')
    )
  gender = models.CharField(max_length=20,choices=Gender_CHOICES, blank=True )
  age = models.IntegerField(default=18,blank=True )
  occupation = models.CharField(max_length=40, blank=True)
  about_you = models.CharField(max_length=500, blank=True)
  intrests = models.ManyToManyField(Intrest, blank=True)
  fb_link = models.URLField(max_length=100, blank=True)
  twitter_link = models.URLField(max_length=100, blank=True)
  insta_link = models.URLField(max_length=100, blank=True)
  def __str__(self):
   return self.user.username


class Plan(models.Model):
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)
  created_on = models.DateTimeField(auto_now_add=True)
  going_time = models.DateTimeField() 
  other_users = models.ManyToManyField(User, blank=True, related_name = 'iplans')
  Food_CHOICES = (
        ('Veg', 'Veg'),
        ('Non-Veg', 'Non-Veg'),
        ('Both', 'Both')
    )
  food_type = models.CharField(max_length=20,choices=Food_CHOICES)
  place = models.PointField()


class Plan_request(models.Model):
  user  = models.ForeignKey(User, on_delete=models.CASCADE)
  created_on = models.DateTimeField(auto_now_add=True)
  Status_CHOICES = (
        ('A', 'Accepted'),
        ('R', 'Rejected'),
        ('P', 'Pending')
    )
  status =  models.CharField(max_length=1, choices=Status_CHOICES, default='P')
  plan = models.ForeignKey(Plan, on_delete=models.SET_NULL, null = True)
  def __str__(self):
   return self.user.username

class Message(models.Model):
  created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)
  message = models.CharField(max_length=400)
  created_on = models.DateTimeField(auto_now_add=True)
  plan = models.ForeignKey(Plan, on_delete=models.CASCADE)

letsdine/forms.py
from mapwidgets.widgets import GooglePointFieldWidget
import re
from django import forms

#from django.contrib.auth.models import User
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete
from django.urls import reverse
from django.contrib.admin import widgets




class PlanForm(forms.ModelForm):
    class Meta:
        model = Plan
        fields = ( "going_time", "other_users", "food_type", "place")
        widgets = {
            'place': GooglePointFieldWidget,
            'other_users': autocomplete.ModelSelect2Multiple(url='user-autocomplete', attrs={'data-html': True}),
            
        }  
        """ 'other_users': autocomplete.ModelSelect2Multiple(url='user-autocomplete', attrs={'data-html': True}),"""      


class RegistrationForm(forms.Form):
	first_name = forms.CharField(max_length=30, label=("First Name"))
	last_name = forms.CharField(max_length=30, label=("Last Name"))
	username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Username"), error_messages={ 'invalid': _("This value must contain only letters, numbers and underscores.") })
	email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=_("Email address"))
	password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password"))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=_("Password (again)"))	
	def clean_username(self):
		username = self.cleaned_data['username']
		if not re.search(r'^\w+$', username):
			raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
		try:
			User.objects.get(username=username)
		except ObjectDoesNotExist:
			return username
		raise forms.ValidationError('Username is already taken.')

	def clean(self):
		if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
			if self.cleaned_data['password1'] != self.cleaned_data['password2']:
				raise forms.ValidationError(_("The two password fields did not match."))
				return self.cleaned_data


class UserForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = '__all__'
		exclude = ('user',)				         

letsdine/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q 
from django.urls import reverse
from django.views import generic
from .forms import *
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.db.models import Q
from datetime import datetime, timedelta
try:
    from django.utils import simplejson as json
except ImportError:
    import json
from dal import autocomplete
from geopy.geocoders import GoogleV3, Nominatim

# Create your views here.

class UserAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        query = UserProfile.objects.all()
        qs = []
        for userp in query:
            qs.append(userp.user)

        if self.q:
            qs = qs.filter( Q(username__icontains = self.q))
        return qs

@csrf_protect 
def register(request):
    if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('letsdine:dashboard'))
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password1'],
            email=form.cleaned_data['email']
            )
            user = User.objects.get(username=form.cleaned_data['username'])
            profile = UserProfile.objects.create(
                user = user
            )
            login(request, user)
            return HttpResponseRedirect(reverse('letsdine:dashboard'))
        else :
            context = {
            'form': form
             } 
            return render(request, 'letsdine/register.html', context)
    else:
        form = RegistrationForm()
        context = {
        'form': form
        }   
        return render(request, 'letsdine/register.html', context)

def index(request):
    return render(request, 'letsdine/index.html')



@login_required(login_url='/login')
def dashboard(request):
    myplans = request.user.iplans.all().order_by('-created_on')[:5]
    planr = request.user.iplans.all().order_by('-created_on')
    requestlist = []
    recentrequestlist = []
    for plan in planr:
        pl = Plan_request.objects.filter(plan=plan)
        for p in pl:
            requestlist.append(p)
    recentrequestlist = sorted(requestlist, key=lambda x: x.created_on, reverse=True)

    geolocator = GoogleV3()
    mypostlist = []
    for plan in myplans:
        x = str(plan.place.x)
        a = plan.place.x
        b = plan.place.y
        y = str(plan.place.y)
        location = geolocator.reverse((b,a))
        mypostlist.append(location[0])
        print location[0]
    user = request.user
    logg = UserProfile.objects.get(user=request.user)
    latest_plans = Plan.objects.order_by('-created_on')[:5]
    geolocator = Nominatim()
    postlist = []
    for plan in latest_plans:
        x = str(plan.place.x)
        a = plan.place.x
        b = plan.place.y

        y = str(plan.place.y)
        location = geolocator.reverse((b,a))
        postlist.append(location)
    print recentrequestlist
    context = {
    'userp' : logg,
    'user' : user,
    'plans' : latest_plans,
    'planz': zip(latest_plans, postlist),
    'myplanz': zip(myplans, mypostlist),
    'recentrequestlist':recentrequestlist,
    }
    return render(request, 'letsdine/dashboard.html', context)


@login_required(login_url='/login')
def edit_profile(request):
    myplans = request.user.iplans.all().order_by('-created_on')[:5]        
    geolocator = Nominatim()
    mypostlist = []
    for plan in myplans:
        x = str(plan.place.x)
        a = plan.place.x
        b = plan.place.y
        y = str(plan.place.y)
        location = geolocator.reverse((b,a))
        mypostlist.append(location)
    if request.method == 'POST':
        user = request.user
        profile = UserProfile.objects.get(user=user)
        form = UserForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            form.save_m2m()
            context = {
            'user' : user,
            'profile' : profile,
            'form'  : form,
            'myplanz': zip(myplans, mypostlist),
            
            }   
            return HttpResponseRedirect(reverse('letsdine:editprofile'), context)
        else :
            context = {
            'user' : user,
            'profile' : profile,
            'form'  : form,
            'myplanz': zip(myplans, mypostlist)
            } 
            return HttpResponseRedirect(reverse('letsdine:editprofile'), context)
    else:    
        user = User.objects.get(username= request.user.username)
        profile = UserProfile.objects.get(user = request.user)
        form = UserForm(request.POST, instance=profile)
        context = {
            'user' : user,
            'profile' : profile,
            'form'  : form,
            'myplanz': zip(myplans, mypostlist)
        }
        return render(request, 'letsdine/editprofile.html', context) 

@login_required(login_url='/login')
def profile(request, username):
    myplans = request.user.iplans.all().order_by('-created_on')[:5]
    geolocator = Nominatim()
    mypostlist = []
    for plan in myplans:
        x = str(plan.place.x)
        a = plan.place.x
        b = plan.place.y
        y = str(plan.place.y)
        location = geolocator.reverse((b,a))
        mypostlist.append(location)
    logg = UserProfile.objects.get(user=request.user)
    loguser = request.user
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(UserProfile, user=user)
    context = {
    'user' : user,
    'userp' : profile,
    'loguser' : loguser,
    'myplanz': zip(myplans, mypostlist)
    }
    return render(request, 'letsdine/prof.html', context)


@login_required(login_url='/login')
def add_plan(request):
    myplans = request.user.iplans.all().order_by('-created_on')[:5]
    geolocator = Nominatim()
    mypostlist = []
    for plan in myplans:
        x = str(plan.place.x)
        a = plan.place.x
        b = plan.place.y
        y = str(plan.place.y)
        location = geolocator.reverse((b,a))
        mypostlist.append(location)
    logg = UserProfile.objects.get(user=request.user)
    if request.method == 'POST':
        form = PlanForm(request.POST)
        user = request.user
        if form.is_valid():
            f = form.save(commit=False)
            f.created_by = request.user
            f.save()
            form.save_m2m()
            if not user in f.other_users.all():
                f.other_users.add(request.user)
                f.save()  
            return HttpResponseRedirect(reverse('letsdine:dashboard'))
        else :
            context = {
        'form': form,
        'logg' : logg,
        'myplanz': zip(myplans, mypostlist)
        }
            return render(request, 'letsdine/create.html', context)
    else:
        logg = UserProfile.objects.get(user=request.user)
        form = PlanForm()
        context = {
        'form': form,
        'logg' : logg,
        'myplanz': zip(myplans, mypostlist)
        }   
        return render(request, 'letsdine/create.html', context)


@login_required(login_url='/login')
def cancelplan(request, plan_id):
    plan = get_object_or_404(Plan, pk=plan_id)
    user = request.user 
    plan.other_users.remove(request.user)
    if plan.other_users.count()==0:
        Plan.objects.filter(id = plan_id).delete()
    return HttpResponseRedirect(reverse('letsdine:dashboard'))


@login_required(login_url='/login')
def requestplan(request, plan_id):
    plan = get_object_or_404(Plan, pk=plan_id)
    user = request.user 
    Plan_request.objects.create(user=user, plan=plan )
    return HttpResponseRedirect(reverse('letsdine:dashboard')) 

@login_required(login_url='/login')
def confirmplan(request, plan_id):
    planreq = get_object_or_404(Plan_request, pk=plan_id)
    plan = planreq.plan
    if not planreq.user in plan.other_users.all():
        plan.other_users.add(planreq.user)
    Plan_request.objects.filter(id=plan_id).delete()    
    return HttpResponseRedirect(reverse('letsdine:dashboard'))

@login_required(login_url='/login')
def rejectplan(request, plan_id):
    Plan_request.objects.filter(id=plan_id).delete()
    return HttpResponseRedirect(reverse('letsdine:dashboard')) 
from django.utils import timezone


@login_required(login_url='/login')
def search(request):
    myplans = request.user.iplans.all().order_by('-created_on')[:5]
    geolocator = Nominatim()
    mypostlist = []
    for plan in myplans:
        x = str(plan.place.x)
        a = plan.place.x
        b = plan.place.y
        y = str(plan.place.y)
        location = geolocator.reverse((b,a))
        mypostlist.append(location)
    if request.method == 'GET':
        allplan = Plan.objects.all()
        query_time= request.GET.get('time')

        query_type= request.GET.get('type', "None")
        if query_time and query_type:
            query_time = datetime.strptime(query_time, "%Y-%m-%d %H:%M:%S")
            start = query_time - timedelta(hours = 1)
            end = query_time + timedelta(hours = 1)
            start = timezone.make_aware(start, timezone.get_current_timezone())
            end = timezone.make_aware(end, timezone.get_current_timezone())
            qs = Plan.objects.filter(created_on__range=(start, end))
            qs = qs.filter(food_type = query_type)
        if query_time and not query_type:

letsdine/templates/letsdine/Search.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
	<title>Search</title>
     <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
<script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
<link rel="stylesheet" href="{% static 'vendor/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Catamaran:900" rel="stylesheet">
<style type="text/css">
        .fa-search:before{
            color: white ;
        }
    </style>
</head>
<body>
<header class="header navbar-fixed-top">
              <nav class="navbar" role="navigation">
                <div class="container">
                      <div class="menu-container js_nav-item">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="toggle-icon"></span>
                        </button>

                          <div class="logo">
                            <a class="logo-wrap" href="{% url 'letsdine:index' %}">
                                <div class="logo_1" style="font-family: 'Satisfy', cursive;font-size: 35px; color: white! important; ">Let's Dine!</div>
                            </a>
                        </div>
                    </div>

                    <div class="collapse navbar-collapse nav-collapse">
                    
                        <div class="menu-container">
                            <ul class="nav navbar-nav navbar-nav-right">
                           

<div id="myModal" class="modal fade" role="dialog" style="z-index: 2000! important;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Notifications</h4>
      </div>
      <div class="modal-body">
        <p>
            <div class="alert alert-success">
  <strong>User1</strong> wants to join you &nbsp;&nbsp;&nbsp;<button class="btn btn-success">Approve</button>&nbsp;&nbsp;&nbsp;<button class="btn btn-danger">Reject</button>

</div>
<div class="alert alert-success">
  <strong>Success!</strong> Indicates a successful or positive action.
</div>
<div class="alert alert-success">
  <strong>Success!</strong> Indicates a successful or positive action.
</div>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% for plan, x in searched %}
<div id="{{ plan.id }}" class="modal fade" role="dialog" style="z-index: 2000! important;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Plan Details</h4>
      </div>
      <div class="modal-body">
        <p style="font-style: 'Catamaran', sans-serif;font-size: 20px;font-weight: bolder;">Following People are going {{ x.address}} on {{ plan.going_time }}<br>
        {% for user in plan.other_users.all %}
        <ul>
        <li> <a href="{% url 'letsdine:profile' user.username %}">{{ user.first_name }}  {{ user.last_name }}</a> </li></ul>

        {% endfor %}</p>
        <center><a  target="_blank" href="https://www.google.com/maps/dir//{{ plan.place.y }},{{ plan.place.x }}/"><img src="https://maps.googleapis.com/maps/api/staticmap?center={{ plan.place.y }},{{ plan.place.x }}&zoom=18&scale=1&size=400x250&maptype=roadmap&key=AIzaSyAi7AkT-8jQgSN9pmT3Y6v5iPi1eCkGIvM&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:1%7C{{ plan.place.y }},{{ plan.place.x }}" alt="Google Map of {{ plan.place.y }},{{ plan.place.x }}"></a></center>
      </div>
      <div class="modal-footer">
       <a href="{% url 'letsdine:requestplan' plan.id %}"> <button class="btn  btn-success">Send Request</button></a><button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endfor %}
{% for plan, x in myplanz %}
<div id="{{ plan.id }}-my" class="modal fade" role="dialog" style="z-index: 2000! important;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Plan Details</h4>
      </div>
      <div class="modal-body">
         <p style="font-style: 'Catamaran', sans-serif;font-size: 20px;font-weight: bolder;">Following People are going {{ x.address}} on {{ plan.going_time }}<br>
        {% for user in plan.other_users.all %}
        <ul>
        <li> <a href="{% url 'letsdine:profile' user.username %}"">{{ user.first_name }}  {{ user.last_name }}</a> </li></ul>
        {% endfor %}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
{% endfor %}

                          
                           <li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover" title="Add plan" href="{% url 'letsdine:add_plan' %}" style="font-family: 'Catamaran', sans-serif;font-size: 20px; line-height: 97px;width: 97px;color: white; "><center><i class="fa fa-plus" aria-hidden="true"></i></center>
</a></li>

                                <li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover" href="{% url 'letsdine:dashboard' %}" style="font-family: 'Catamaran', sans-serif;font-size: 20px; line-height: 97px;width: 97px;color: white; "><center><i class="fa fa-home" aria-hidden="true"></i></center>
</a></li>
<li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover" href="{% url 'letsdine:search' %}" style="font-family: 'Catamaran', sans-serif;font-size: 20px; line-height: 97px;width: 97px;color: white; "><center><i class="fa fa-search" aria-hidden="true"></i></center>
</a></li>
                                <li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover" href="{% url 'letsdine:profile' request.user.username %}" style="font-family: 'Catamaran', sans-serif;font-size: 20px"><img src="{{ user.userprofile.display_pic.url }}" width="97px" height="97px"></a></li>
                                <li class="js_nav-item nav-item"><a class="nav-item-child nav-item-hover" href="{% url 'letsdine:logout' %}" style="font-family: 'Catamaran', sans-serif;font-size: 20px; line-height: 97px;width: 97px;color: white; "><center><i class="fa fa-sign-out" aria-hidden="true"></i></center>
</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
            </header>

            <div class="row" style="height: 97px;"></div>
<div class="wrapper">
    <div class="row" class="height_nav">
        <div class="col-sm-3" style="background-color: #232b2d" >
        <div class="row">
            <div class="welcome" style="height: 150px;">
                <div class="row" style="height: 30px;"></div>
                <div class="row"><center><img src="{{ user.userprofile.display_pic.url }}" width="50px" height="50px" style="border-radius: 50%;"></center></div><br>
                <div class="row" style=" color: white; font-style: 'Catamaran', sans-serif;font-size: 20px;font-weight: bolder;"><center>WELCOME</center></div>

            </div>
        </div>
        <hr>
        <br>
        <br>
            <div class="row" >
                <div class="col-sm-2"></div>
                <div class="col-sm-8" class="" >
                {% for plan, x in myplanz %}
                <a data-toggle="modal" data-target="#{{ plan.id }}-my">
                    <div class="myplan" style="cursor: pointer;">

                    <div class="myplan1"> 
                       <center> Going {{ x.address}} on {{ plan.going_time }} . {{ plan.other_users.count }} people interested.</center> 
                        </div><br>
                        <center><a href="{% url 'letsdine:cancelplan' plan.id %}"><button class="btn btn-danger">Cancel Plan</button></a></center>
                    </div><br>
                    </a>
                    {% endfor %}
                </div>
                <div class="col-sm-2"></div>
            </div>
        </div>
        <br><br>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-12" class="body_height">
                    <div class="row">
                    
                              <div id="search5back">

    <form action=".">
       <div class="row"><center>
       <div class="col-md-1"></div>
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label>City</label>
                                                <input type="text" id="id_going_time" class="form-control" placeholder="Time" name="time">
                                            </div>
                                        </div>
                                        <div class="col-md-5">
                                            <div class="form-group">
                                                <label>Type</label><br>
                                                 <select class="form-control" id="id_gender" name="type" >
                                                <option value="Veg">Veg</option>
                                                <option value="Non-Veg">Non-Veg</option>
                                                <option value="Both">Both</option>
                                                </select>
                                            </div>
                                        </div>
                                        </center>
                                    </div>
        <br/>
        <br>
                    <div class="row">
                    <center><button class="btn btn-success" type="submit">Submit</button>
                    </div>

    </form>
</div>
                        </div>
                       
                    </div>
                    <br/>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                     {% for plan, x in searched %}
                    <div class="row">
                        <div class="otherplans" style="cursor: pointer;">
                        <a data-toggle="modal" data-target="#{{ plan.id }}">
                        <div class="otherplan">
                            <div class="row">
                                <div class="plan">
                                    Going {{ x.address}} on {{ plan.going_time }} . {{ plan.other_users.count }} people interested.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'letsdine:requestplan' plan.id %}"><button class="btn btn-success" type="submit">Send Request</button>
                                    
                                </div>

                            </div>
                        </div>
                        </a>
                         </div>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<footer>
    <div class="row">
    <div class="col-sm-6">
        <center><div style="font-family: 'Satisfy', cursive;font-size: 45px; color: white;">Let's Dine!</div></center>
        </div>
        <div class="col-sm-6">
            <div style="font-family: 'Catamaran', sans-serif; font-size: 35px; color: white;">Made By Team - The Shinigamis</div>
        </div>
    </div>
</footer>
<script src="{% static 'vendor/jquery.min.js' %}' %}" type="text/javascript"></script>
        <script src="{% static 'vendor/jquery-migrate.min.js' %}' %}" type="text/javascript"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}' %}" type="text/javascript"></script>
        <script type="text/javascript" src="{% static 'js/javascript.js' %}' %}"></script>
        <script>
    $(function () {
        $('#id_going_time').datetimepicker({
            format:'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>
</body>
</html>